export const lightTheme = {
  CARD_BACKGROUND: '#ffffff',
  CARD_FONT_COLOR: '#474554',
  FONT_COLOR: '#474554',
  SECOND_COLOR: '#C2C2C2',
  SCREEN_BACKGROUND: '#fafafa',
  RECORD_BACKGROUND: '#efefef',
  CARD_SHADOW: 'rgba(0, 0, 0, 0.2)',
  PLAYER_BACKGROUND: '#EFEFEF',
  RECORDER_BACKGROUND: '#efefef'
};
export const darkTheme = {
  CARD_BACKGROUND: '#121212',
  CARD_FONT_COLOR: '#fff',
  FONT_COLOR: '#fff',
  SECOND_COLOR: '#5D5D5D',
  SCREEN_BACKGROUND: '#000',
  RECORD_BACKGROUND: '#2d2d2d',
  CARD_SHADOW: 'rgba(255, 255, 255, 0.05)',
  PLAYER_BACKGROUND: '#2E2E2E',
  RECORDER_BACKGROUND: '#121212'
};
// export const darkTheme = {
//   CARD_BACKGROUND: '#2C2D2D',
//   CARD_FONT_COLOR: '#D8D9D9',
//   FONT_COLOR: '#D8D9D9',
//   SECOND_COLOR: '#C2C2C2',
//   SCREEN_BACKGROUND: '#232526'
// };
