export const lightTheme = {
  CARD_BACKGROUND: '#ffffff',
  CARD_FONT_COLOR: '#474554',
  FONT_COLOR: '#474554',
  SECOND_COLOR: '#C2C2C2',
  SCREEN_BACKGROUND: '#fafafa'
};
export const darkTheme = {
  CARD_BACKGROUND: '#2C2D2D',
  CARD_FONT_COLOR: '#D8D9D9',
  FONT_COLOR: '#D8D9D9',
  SECOND_COLOR: '#C2C2C2',
  SCREEN_BACKGROUND: '#232526'
};
